"""Turn Voikko-validated generated content into a Supabase seed.

Reads scripts/generate/out/generated_content.json (the validated items from
generate.py / run_batch.py) and emits:

  out/generated_sentences.sql      idempotent INSERTs into the sentences table.
                                   Only the Voikko-validated KIRJAKIELI ships;
                                   puhekieli is NULL (it is not morphologically
                                   validated and must be human-verified first —
                                   same rule as scripts/ingest/).
  out/generated_puhekieli_REVIEW.tsv   the generated puhekieli for a Finnish
                                   speaker to verify before it is loaded.

The owner runs the .sql once in the Supabase SQL editor (ON CONFLICT DO NOTHING).
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent / "out"

_VALID_LEVELS = {"A1", "A2", "B1", "B2", "C1", "C2"}


def _sql_str(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def _topic_subselect(slug: str | None) -> str:
    return f"(SELECT id FROM topics WHERE slug = {_sql_str(slug)})" if slug else "NULL"


def emit(items: list[dict]) -> tuple[str, str]:
    """Return (sentences_sql, puhekieli_review_tsv) from validated items.

    Each item: kirjakieli, puhekieli, translation_en, _topic_slug, _level.
    Pure and testable.
    """
    rows: list[str] = []
    review = ["# kirjakieli\tpuhekieli_GENERATED (UNVERIFIED — Finnish speaker must approve)\ttopic\tlevel"]
    for it in items:
        kirja = (it.get("kirjakieli") or "").strip()
        if not kirja:
            continue
        gloss = (it.get("translation_en") or "").strip()
        level = it.get("_level") if it.get("_level") in _VALID_LEVELS else "A2"
        slug = it.get("_topic_slug")
        rows.append(
            f"  ({_sql_str(kirja)}, NULL, {_sql_str(gloss)}, {_sql_str(level)}, {_topic_subselect(slug)})"
        )
        puhe = (it.get("puhekieli") or "").strip()
        review.append(f"{kirja}\t{puhe}\t{slug or ''}\t{level}")

    header = (
        "-- PuhuScribe generated sentences (grounded + Voikko-validated kirjakieli)\n"
        f"-- GENERATED by scripts/generate on {date.today().isoformat()} — do not hand-edit.\n"
        "-- Every kirjakieli form was validated as real Finnish by Voikko (libvoikko + voikko-fi)\n"
        "-- and grounded in data/finnish_frequency_lemmas.json. puhekieli is NULL on purpose —\n"
        "-- it is not morphologically validated and must be human-verified first\n"
        "-- (see out/generated_puhekieli_REVIEW.tsv).\n\n"
    )
    if not rows:
        sql = header + "-- no validated items to insert\n"
    else:
        sql = (
            header
            + "INSERT INTO sentences (kirjakieli, puhekieli, translation_en, level, topic_id) VALUES\n"
            + ",\n".join(rows)
            + "\nON CONFLICT DO NOTHING;\n"
        )
    return sql, "\n".join(review) + "\n"


def main():
    src = OUT_DIR / "generated_content.json"
    if not src.exists():
        raise SystemExit(f"no input at {src} — run generate.py / run_batch.py first")
    data = json.loads(src.read_text(encoding="utf-8"))
    items = data.get("items", [])
    sql, review = emit(items)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "generated_sentences.sql").write_text(sql, encoding="utf-8")
    (OUT_DIR / "generated_puhekieli_REVIEW.tsv").write_text(review, encoding="utf-8")
    print(f"Wrote {OUT_DIR/'generated_sentences.sql'} ({len(items)} items; puhekieli NULL)")
    print(f"Wrote {OUT_DIR/'generated_puhekieli_REVIEW.tsv'} — verify before loading puhekieli")


if __name__ == "__main__":
    main()
