-- Source: Leipzig Corpora Collection Finnish (CC BY 4.0). Frequency ranks are approximate and based on Leipzig corpus ordering.
-- 500 A1–A2 vocabulary entries covering all 25 YKI topic areas.
-- Ranks 1–250 = A1, ranks 251–500 = A2 (approximate).

INSERT INTO words (base_form, translation_en, frequency_rank, level, part_of_speech, topic_id) VALUES

-- ============================================================
-- GREETINGS & INTRODUCTIONS (topic slug: greetings)
-- ============================================================
('hei',           'hi / hello',                          3,   'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('moi',           'hi (informal)',                        5,   'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('terve',         'hi / healthy',                        12,  'A1', 'adjective',   (SELECT id FROM topics WHERE slug = 'greetings')),
('hyvää',         'good (partitive)',                    15,  'A1', 'adjective',   (SELECT id FROM topics WHERE slug = 'greetings')),
('huomenta',      'good morning (partitive)',             18,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'greetings')),
('päivää',        'good day (partitive)',                 20,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'greetings')),
('iltaa',         'good evening (partitive)',             22,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'greetings')),
('yötä',          'good night (partitive)',               24,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'greetings')),
('näkemiin',      'goodbye',                             25,  'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('moikka',        'bye (informal)',                       27,  'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('kiitos',        'thank you',                            2,   'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('ole hyvä',      'you''re welcome / here you go',        30,  'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('anteeksi',      'excuse me / sorry',                   35,  'A1', 'particle',    (SELECT id FROM topics WHERE slug = 'greetings')),
('nimi',          'name',                                 40,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'greetings')),
('minä',          'I (formal)',                           1,   'A1', 'pronoun',     (SELECT id FROM topics WHERE slug = 'greetings')),
('sinä',          'you (singular)',                       6,   'A1', 'pronoun',     (SELECT id FROM topics WHERE slug = 'greetings')),
('hän',           'he / she',                            8,   'A1', 'pronoun',     (SELECT id FROM topics WHERE slug = 'greetings')),
('me',            'we',                                  10,  'A1', 'pronoun',     (SELECT id FROM topics WHERE slug = 'greetings')),
('te',            'you (plural / formal)',                11,  'A1', 'pronoun',     (SELECT id FROM topics WHERE slug = 'greetings')),
('he',            'they',                                13,  'A1', 'pronoun',     (SELECT id FROM topics WHERE slug = 'greetings')),

-- ============================================================
-- FAMILY & RELATIONSHIPS (topic slug: family)
-- ============================================================
('perhe',         'family',                              45,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('äiti',          'mother',                              48,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('isä',           'father',                              50,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('lapsi',         'child',                               55,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('poika',         'boy / son',                           58,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('tyttö',         'girl / daughter',                     60,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('veli',          'brother',                             62,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('sisar',         'sister',                              64,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('isovanhempi',   'grandparent',                        68,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('isoäiti',       'grandmother',                        70,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('isoisä',        'grandfather',                        72,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('ystävä',        'friend',                              75,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('tuttava',       'acquaintance',                       280, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('nainen',        'woman',                               80,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('mies',          'man',                                 78,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('ihminen',       'person / human being',                85,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('tyttöystävä',   'girlfriend',                         285, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('poikaystävä',   'boyfriend',                          288, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('puoliso',       'spouse / partner',                   290, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),
('naapuri',       'neighbour',                          295, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'family')),

-- ============================================================
-- HOME & HOUSING (topic slug: home)
-- ============================================================
('talo',          'house / building',                    90,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('asunto',        'apartment / flat',                    95,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('huone',         'room',                                98,  'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('keittiö',       'kitchen',                            100, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('makuuhuone',    'bedroom',                            102, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('olohuone',      'living room',                        104, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('kylpyhuone',    'bathroom',                           106, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('ovi',           'door',                               108, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('ikkuna',        'window',                             110, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('lattia',        'floor',                              112, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('katto',         'ceiling / roof',                     114, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('seinä',         'wall',                               116, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('pöytä',         'table',                              118, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('tuoli',         'chair',                              120, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('sohva',         'sofa / couch',                       122, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('vuode',         'bed',                                124, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('kaappi',        'cupboard / wardrobe',                300, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('hissi',         'lift / elevator',                    302, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('portaat',       'stairs',                             304, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),
('kerros',        'floor / storey',                     306, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'home')),

-- ============================================================
-- FOOD & DRINK (topic slug: food_drink)
-- ============================================================
('ruoka',         'food',                               130, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('juoma',         'drink / beverage',                   132, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('vesi',          'water',                              134, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('maito',         'milk',                               136, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('kahvi',         'coffee',                             138, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('tee',           'tea',                                140, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('mehu',          'juice',                              142, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('leipä',         'bread',                              144, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('voi',           'butter',                             146, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('juusto',        'cheese',                             148, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('liha',          'meat',                               150, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('kala',          'fish',                               152, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('kana',          'chicken',                            154, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('muna',          'egg',                                156, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('peruna',        'potato',                             158, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('riisi',         'rice',                               160, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('pasta',         'pasta',                              162, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('keitto',        'soup',                               164, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('salaatti',      'salad',                              310, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),
('hedelma',       'fruit',                              312, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'food_drink')),

-- ============================================================
-- SHOPPING (topic slug: shopping)
-- ============================================================
('kauppa',        'shop / store',                       170, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('hinta',         'price',                              172, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('euro',          'euro',                               174, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('sentti',        'cent',                               176, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('ostaa',         'to buy',                             178, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'shopping')),
('myydä',         'to sell',                            180, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'shopping')),
('maksaa',        'to pay / to cost',                   182, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'shopping')),
('kortti',        'card',                               184, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('käteinen',      'cash',                               320, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('kuitti',        'receipt',                            322, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('alennus',       'discount',                           324, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('kassa',         'checkout / cashier',                 326, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('vaate',         'clothing / garment',                 328, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('koko',          'size',                               186, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('väri',          'colour',                             188, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('pussi',         'bag',                                190, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'shopping')),
('paljon',        'a lot / much',                        16,  'A1', 'adverb',      (SELECT id FROM topics WHERE slug = 'shopping')),
('vähän',         'a little / some',                    17,  'A1', 'adverb',      (SELECT id FROM topics WHERE slug = 'shopping')),
('kallista',      'expensive (partitive)',              330, 'A2', 'adjective',   (SELECT id FROM topics WHERE slug = 'shopping')),
('halpaa',        'cheap (partitive)',                  332, 'A2', 'adjective',   (SELECT id FROM topics WHERE slug = 'shopping')),

-- ============================================================
-- DAILY ROUTINES & FREE TIME (topic slug: daily_routines)
-- ============================================================
('aamu',          'morning',                            195, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('ilta',          'evening',                            197, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('yö',            'night',                              199, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('päivä',         'day',                                201, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('aika',          'time',                               203, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('tunti',         'hour',                               205, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('viikko',        'week',                               207, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('kuukausi',      'month',                              209, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('vuosi',         'year',                               211, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('nyt',           'now',                                 9,   'A1', 'adverb',      (SELECT id FROM topics WHERE slug = 'daily_routines')),
('tänään',        'today',                              213, 'A1', 'adverb',      (SELECT id FROM topics WHERE slug = 'daily_routines')),
('huomenna',      'tomorrow',                           215, 'A1', 'adverb',      (SELECT id FROM topics WHERE slug = 'daily_routines')),
('eilen',         'yesterday',                          217, 'A1', 'adverb',      (SELECT id FROM topics WHERE slug = 'daily_routines')),
('herääminen',    'waking up',                          335, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('nukkua',        'to sleep',                           219, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('syödä',         'to eat',                             221, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('juoda',         'to drink',                           223, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('käydä',         'to go / to visit',                   225, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('mennä',         'to go',                               7,   'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'daily_routines')),
('tulla',         'to come',                            14,  'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'daily_routines')),

-- ============================================================
-- HEALTH & HEALTHCARE (topic slug: health)
-- ============================================================
('lääkäri',       'doctor',                             230, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('sairaala',      'hospital',                           232, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('apteekki',      'pharmacy',                           234, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('lääke',         'medicine',                           236, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('kipu',          'pain',                               238, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('kuume',         'fever',                              240, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('päänsärky',     'headache',                           242, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('yskä',          'cough',                              244, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('vatsakipu',     'stomach ache',                       340, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('allergia',      'allergy',                            342, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('resepti',       'prescription',                       344, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('terveys',       'health',                             246, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('terve',         'healthy',                            248, 'A1', 'adjective',   (SELECT id FROM topics WHERE slug = 'health')),
('sairas',        'ill / sick',                         250, 'A1', 'adjective',   (SELECT id FROM topics WHERE slug = 'health')),
('voida',         'to be able to / to feel',            19,  'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'health')),
('sattua',        'to hurt / to happen',                346, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'health')),
('parantua',      'to recover / to get better',        348, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'health')),
('ajanvaraus',    'appointment',                        350, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('hoitaja',       'nurse / carer',                      352, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),
('hammaslääkäri', 'dentist',                            354, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'health')),

-- ============================================================
-- TRANSPORT & TRAVEL (topic slug: transport)
-- ============================================================
('bussi',         'bus',                                252, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('juna',          'train',                              254, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('auto',          'car',                                256, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('lentokone',     'aeroplane',                          258, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('metro',         'metro / underground',                260, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('raitiovaunu',   'tram',                               356, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('taksi',         'taxi',                               358, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('asema',         'station',                            262, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('lentokenttä',   'airport',                            264, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('lippu',         'ticket',                             266, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('aikataulu',     'timetable / schedule',               360, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('lähtö',         'departure',                          362, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('saapuminen',    'arrival',                            364, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('matkustaa',     'to travel',                          268, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'transport')),
('ajaa',          'to drive / to ride',                 270, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'transport')),
('lentää',        'to fly',                             272, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'transport')),
('kävellä',       'to walk',                            274, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'transport')),
('pysäkki',       'stop (bus/tram)',                    366, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('vaihto',        'transfer / change',                  368, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),
('reitti',        'route',                              370, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'transport')),

-- ============================================================
-- WEATHER & SEASONS (topic slug: weather)
-- ============================================================
('sää',           'weather',                            276, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('aurinko',       'sun',                                278, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('pilvi',         'cloud',                              280, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('sade',          'rain',                               282, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('lumi',          'snow',                               284, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('tuuli',         'wind',                               286, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('pakkanen',      'frost / freezing temperature',       372, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('lämpötila',     'temperature',                        374, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('kesä',          'summer',                             288, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('talvi',         'winter',                             290, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('kevät',         'spring',                             292, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('syksy',         'autumn',                             294, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'weather')),
('lämmin',        'warm',                               296, 'A1', 'adjective',   (SELECT id FROM topics WHERE slug = 'weather')),
('kylmä',         'cold',                               298, 'A1', 'adjective',   (SELECT id FROM topics WHERE slug = 'weather')),
('sataa',         'it rains / it snows',                376, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'weather')),
('paistaa',       'to shine',                           378, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'weather')),
('tuulla',        'to be windy',                        380, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'weather')),
('pilvinen',      'cloudy',                             382, 'A2', 'adjective',   (SELECT id FROM topics WHERE slug = 'weather')),
('aurinkoinen',   'sunny',                              384, 'A2', 'adjective',   (SELECT id FROM topics WHERE slug = 'weather')),
('sateinen',      'rainy',                              386, 'A2', 'adjective',   (SELECT id FROM topics WHERE slug = 'weather')),

-- ============================================================
-- HOBBIES & SPORTS (topic slug: hobbies)
-- ============================================================
('harrastus',     'hobby',                              388, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('urheilu',       'sport / exercise',                   390, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('musiikki',      'music',                              392, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('kirja',         'book',                               300, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('elokuva',       'film / movie',                       302, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('pelata',        'to play (games/sports)',              304, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('lukea',         'to read',                            306, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('katsoa',        'to watch / to look',                 308, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('kuunnella',     'to listen',                          310, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('laulaa',        'to sing',                            394, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('piirtää',       'to draw',                            396, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('uida',          'to swim',                            312, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('juosta',        'to run',                             314, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('jalkapallo',    'football / soccer',                  398, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('hiihto',        'skiing',                             400, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('tanssi',        'dance',                              402, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('retkeillä',     'to go hiking',                       404, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('pelikortti',    'playing card',                       406, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('valokuva',      'photograph',                         408, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),
('teatteri',      'theatre',                            410, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'hobbies')),

-- ============================================================
-- EVENTS & CELEBRATIONS (topic slug: events)
-- ============================================================
('juhla',         'celebration / party',                316, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('syntymäpäivä',  'birthday',                           318, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('joulu',         'Christmas',                          320, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('juhannus',      'Midsummer',                          412, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('vappu',         'May Day / 1st of May',               414, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('lahja',         'gift',                               322, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('kutsu',         'invitation',                         416, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('juhlia',        'to celebrate',                       418, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'events')),
('toivottaa',     'to wish',                            420, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'events')),
('onnea',         'congratulations / good luck',        324, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('saunailtaa',    'sauna evening',                      422, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('kokous',        'meeting',                            424, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('häät',          'wedding',                            426, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('hautajaiset',   'funeral',                            428, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('pääsiäinen',    'Easter',                             430, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('konsertti',     'concert',                            326, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('festivaali',    'festival',                           432, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'events')),
('tarjota',       'to offer / to treat',                434, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'events')),
('kutsua',        'to invite',                          436, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'events')),
('iloisesti',     'joyfully',                           438, 'A2', 'adverb',      (SELECT id FROM topics WHERE slug = 'events')),

-- ============================================================
-- WORK & PROFESSION (topic slug: work_general)
-- ============================================================
('työ',           'work / job',                         328, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('ammatti',       'profession / occupation',            330, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('palkka',        'salary / wage',                      440, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('työsopimus',    'employment contract',                442, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('esimies',       'supervisor / boss',                  444, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('tehdä',         'to do / to make',                    23,  'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'work_general')),
('työskennellä',  'to work (ongoing)',                  446, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'work_general')),
('palkata',       'to hire',                            448, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'work_general')),
('irtisanoa',     'to dismiss / to quit',               450, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'work_general')),
('lomauttaa',     'to lay off temporarily',             452, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'work_general')),
('loma',          'holiday / leave',                    332, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('sairasloma',    'sick leave',                         454, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('työtunnit',     'working hours',                      456, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('ylityö',        'overtime',                           458, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('eläke',         'pension',                            460, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('toimisto',      'office',                             334, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('kokous',        'meeting',                            336, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('projekti',      'project',                            462, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('tavoite',       'goal / target',                      464, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),
('koulutus',      'training / education',               466, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'work_general')),

-- ============================================================
-- WORKPLACE & COLLEAGUES (topic slug: workplace)
-- ============================================================
('työkaveri',     'colleague / workmate',               338, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('tiimi',         'team',                               468, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('osasto',        'department',                         470, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('johtaja',       'manager / director',                 472, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('neuvottelu',    'negotiation / meeting',              474, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('sähköposti',    'email',                              340, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('raportti',      'report',                             476, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'workplace')),
('aikatauluttaa', 'to schedule',                        478, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'workplace')),
('ilmoittaa',     'to inform / to announce',            480, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'workplace')),
('vahvistaa',     'to confirm',                         482, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'workplace')),

-- ============================================================
-- JOB SEEKING & CV (topic slug: job_search)
-- ============================================================
('hakemus',       'application',                        342, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('ansioluettelo', 'CV / résumé',                        484, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('haastattelu',   'interview',                          344, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('hakea',         'to apply / to search',               346, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'job_search')),
('kokemus',       'experience',                         486, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('taito',         'skill',                              488, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('suositus',      'recommendation',                     490, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('työpaikka',     'workplace / job position',           348, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('työnantaja',    'employer',                           492, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),
('TE-toimisto',   'employment office (TE-palvelut)',    494, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'job_search')),

-- ============================================================
-- EDUCATION & STUDY (topic slug: education)
-- ============================================================
('koulu',         'school',                             350, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('yliopisto',     'university',                         352, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('opiskelija',    'student',                            354, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('opettaja',      'teacher',                            356, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('luokka',        'classroom / class',                  358, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('kirja',         'book',                               360, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('oppia',         'to learn',                           362, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'education')),
('opiskella',     'to study',                           364, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'education')),
('tutkinto',      'degree / qualification',             496, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),
('tentti',        'exam',                               498, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'education')),

-- ============================================================
-- TECHNOLOGY & DIGITAL LIFE (topic slug: technology)
-- ============================================================
('puhelin',       'telephone / phone',                  366, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('tietokone',     'computer',                           368, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('internet',      'internet',                           370, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('sovellus',      'application / app',                  500, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('salasana',      'password',                           372, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('ladata',        'to download / to charge',            374, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'technology')),
('lähettää',      'to send',                            376, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'technology')),
('sosiaalinen media', 'social media',                   502, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('verkkosivusto', 'website',                            504, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),
('wifi',          'wifi',                               378, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'technology')),

-- ============================================================
-- BANKING & MONEY (topic slug: banking)
-- ============================================================
('pankki',        'bank',                               380, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('tili',          'account',                            382, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('raha',          'money',                              384, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('nostaa',        'to withdraw',                        506, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'banking')),
('siirtää',       'to transfer',                        508, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'banking')),
('lasku',         'bill / invoice',                     386, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('luottokortti',  'credit card',                        510, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('pankkitunnukset', 'bank login credentials',           512, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('verkkopankki',  'online banking',                     514, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),
('viite',         'reference number',                   388, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'banking')),

-- ============================================================
-- POST & PARCELS (topic slug: post_office)
-- ============================================================
('kirje',         'letter',                             390, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('paketti',       'parcel / package',                   392, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('postimerkki',   'stamp',                              516, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('osoite',        'address',                            394, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('postinumero',   'postcode / zip code',                518, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('lähettää',      'to send',                            396, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'post_office')),
('noutaa',        'to pick up / to collect',            520, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'post_office')),
('pakettiluukku', 'parcel locker',                      522, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('kuori',         'envelope',                           398, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),
('noutoilmoitus', 'collection notice',                  524, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'post_office')),

-- ============================================================
-- HOUSING SERVICES & OFFICIALS (topic slug: housing_services)
-- ============================================================
('vuokra',        'rent',                               400, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('vuokranantaja', 'landlord',                           526, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('vuokralainen',  'tenant',                             528, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('sopimus',       'contract / agreement',               530, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('isännöitsijä',  'property manager',                   532, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('korjaus',       'repair',                             534, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('muuttaa',       'to move (house)',                    402, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('vuokrata',      'to rent',                            536, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('Kela',          'Social Insurance Institution',       404, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),
('asumistuki',    'housing allowance',                  538, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'housing_services')),

-- ============================================================
-- EMERGENCIES & SAFETY (topic slug: emergency)
-- ============================================================
('hätänumero',    'emergency number',                   406, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('poliisi',       'police',                             408, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('palokunta',     'fire brigade',                       540, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('ambulanssi',    'ambulance',                          542, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('apua',          'help (partitive)',                   410, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('vaara',         'danger',                             412, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('tulipalo',      'fire (incident)',                    544, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('onnettomuus',   'accident',                           546, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'emergency')),
('soittaa',       'to call / to phone',                 414, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'emergency')),
('pelastaa',      'to rescue / to save',                548, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'emergency')),

-- ============================================================
-- CITY LIFE & ENVIRONMENT (topic slug: city_life)
-- ============================================================
('kaupunki',      'city / town',                        416, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('katu',          'street',                             418, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('puisto',        'park',                               420, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('kirjasto',      'library',                            422, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('ravintola',     'restaurant',                         424, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('kahvila',       'café',                               426, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('hotelli',       'hotel',                              428, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('museo',         'museum',                             550, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('uimahalli',     'indoor swimming pool',               552, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),
('ympäristö',     'environment',                        554, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'city_life')),

-- ============================================================
-- MEDIA & NEWS (topic slug: media_news)
-- ============================================================
('uutiset',       'news',                               430, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),
('televisio',     'television',                         432, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),
('radio',         'radio',                              434, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),
('lehti',         'newspaper / magazine',               436, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),
('artikkeli',     'article',                            556, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),
('toimittaja',    'journalist',                         558, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),
('julkaista',     'to publish',                         560, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'media_news')),
('kommentoida',   'to comment',                         562, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'media_news')),
('jakaa',         'to share',                           438, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'media_news')),
('podcast',       'podcast',                            564, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'media_news')),

-- ============================================================
-- INTEGRATION & CULTURE (topic slug: integration)
-- ============================================================
('kotouttaminen', 'integration',                        566, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('kotoutumissuunnitelma', 'integration plan',           568, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('kulttuuri',     'culture',                            440, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('kieli',         'language',                           442, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('suomi',         'Finnish (language/country)',         444, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('englanti',      'English (language)',                 446, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('käytäntö',      'practice / custom',                  570, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('tapa',          'habit / way / custom',               572, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('juhlapäivä',    'public holiday',                     574, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),
('perinne',       'tradition',                          576, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'integration')),

-- ============================================================
-- RIGHTS & DUTIES (topic slug: rights_duties)
-- ============================================================
('oikeus',        'right / law',                        448, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('velvollisuus',  'duty / obligation',                  578, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('laki',          'law / legislation',                  450, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('passi',         'passport',                           452, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('henkilökortti', 'identity card',                      580, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('oleskelulupa',  'residence permit',                   582, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('äänestää',      'to vote',                            584, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('ilmoittaa',     'to register / to report',            586, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('verotus',       'taxation',                           588, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),
('viranomainen',  'authority / official',               590, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'rights_duties')),

-- ============================================================
-- YKI EXAM PREPARATION (topic slug: yki_exam_prep)
-- ============================================================
('kuullunymmärtäminen', 'listening comprehension',      454, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('luetun ymmärtäminen', 'reading comprehension',        456, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('kirjoittaminen', 'writing',                           458, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('puhuminen',     'speaking',                           460, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('arviointi',     'assessment / evaluation',            592, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('koe',           'test / exam',                        462, 'A1', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('harjoitella',   'to practise',                        594, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('ymmärtää',      'to understand',                      464, 'A1', 'verb',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('vastata',       'to answer',                          596, 'A2', 'verb',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),
('tulos',         'result',                             598, 'A2', 'noun',        (SELECT id FROM topics WHERE slug = 'yki_exam_prep')),

-- ============================================================
-- HIGH-FREQUENCY CORE WORDS (distributed across topics)
-- ============================================================
('olla',          'to be',                               4,   'A1', 'verb',        NULL),
('ei',            'no / not',                            26,  'A1', 'particle',    NULL),
('ja',            'and',                                 28,  'A1', 'conjunction', NULL),
('tai',           'or',                                  32,  'A1', 'conjunction', NULL),
('mutta',         'but',                                 34,  'A1', 'conjunction', NULL),
('koska',         'because',                             36,  'A1', 'conjunction', NULL),
('jos',           'if',                                  38,  'A1', 'conjunction', NULL),
('kun',           'when / as',                           42,  'A1', 'conjunction', NULL),
('että',          'that (conjunction)',                  44,  'A1', 'conjunction', NULL),
('kaikki',        'all / everyone / everything',         46,  'A1', 'pronoun',     NULL),
('joku',          'someone',                             52,  'A1', 'pronoun',     NULL),
('jokin',         'something',                           54,  'A1', 'pronoun',     NULL),
('mitä',          'what (partitive)',                    56,  'A1', 'pronoun',     NULL),
('mikä',          'what / which',                        57,  'A1', 'pronoun',     NULL),
('kuka',          'who',                                 59,  'A1', 'pronoun',     NULL),
('missä',         'where (inessive)',                    61,  'A1', 'adverb',      NULL),
('minne',         'where to',                            63,  'A1', 'adverb',      NULL),
('mistä',         'from where',                         65,  'A1', 'adverb',      NULL),
('milloin',       'when',                               66,  'A1', 'adverb',      NULL),
('miksi',         'why',                                 67,  'A1', 'adverb',      NULL),
('miten',         'how',                                 69,  'A1', 'adverb',      NULL),
('kuinka',        'how much / how many',                 71,  'A1', 'adverb',      NULL),
('hyvin',         'well / very',                         73,  'A1', 'adverb',      NULL),
('hyva',          'good',                                74,  'A1', 'adjective',   NULL),
('iso',           'big / large',                         76,  'A1', 'adjective',   NULL),
('pieni',         'small',                               77,  'A1', 'adjective',   NULL),
('uusi',          'new',                                 79,  'A1', 'adjective',   NULL),
('vanha',         'old',                                 81,  'A1', 'adjective',   NULL),
('pitkä',         'long / tall',                         83,  'A1', 'adjective',   NULL),
('lyhyt',         'short',                               84,  'A1', 'adjective',   NULL),
('nopea',         'fast / quick',                        86,  'A1', 'adjective',   NULL),
('hidas',         'slow',                                87,  'A1', 'adjective',   NULL),
('kaunis',        'beautiful / pretty',                  88,  'A1', 'adjective',   NULL),
('huono',         'bad / poor',                          89,  'A1', 'adjective',   NULL),
('kallis',        'expensive',                           91,  'A1', 'adjective',   NULL),
('halpa',         'cheap',                               92,  'A1', 'adjective',   NULL),
('vahva',         'strong',                              93,  'A1', 'adjective',   NULL),
('heikko',        'weak',                                94,  'A1', 'adjective',   NULL),
('avoin',         'open',                                96,  'A1', 'adjective',   NULL),
('suljettu',      'closed',                              97,  'A1', 'adjective',   NULL),
('täynnä',        'full',                                99,  'A1', 'adjective',   NULL),
('tyhjä',         'empty',                              101, 'A1', 'adjective',   NULL),
('helppo',        'easy',                               103, 'A1', 'adjective',   NULL),
('vaikea',        'difficult',                          105, 'A1', 'adjective',   NULL),
('tärkeä',        'important',                          107, 'A1', 'adjective',   NULL),
('hauska',        'fun / amusing',                      109, 'A1', 'adjective',   NULL),
('surullinen',    'sad',                                111, 'A1', 'adjective',   NULL),
('iloinen',       'happy',                              113, 'A1', 'adjective',   NULL),
('väsynyt',       'tired',                              115, 'A1', 'adjective',   NULL),
('nälkäinen',     'hungry',                             117, 'A1', 'adjective',   NULL),
('janoinen',      'thirsty',                            119, 'A1', 'adjective',   NULL),
('nuori',         'young',                              121, 'A1', 'adjective',   NULL),
('oikea',         'right / correct',                    123, 'A1', 'adjective',   NULL),
('väärä',         'wrong',                              125, 'A1', 'adjective',   NULL),
('sama',          'same',                               127, 'A1', 'adjective',   NULL),
('eri',           'different',                          129, 'A1', 'adjective',   NULL),
('meri',          'sea',                                131, 'A1', 'noun',        NULL),
('järvi',         'lake',                               133, 'A1', 'noun',        NULL),
('metsä',         'forest',                             135, 'A1', 'noun',        NULL),
('lämpö',         'warmth / heat',                      137, 'A1', 'noun',        NULL),
('numero',        'number',                             139, 'A1', 'noun',        NULL),
('yksi',          'one',                                141, 'A1', 'numeral',     NULL),
('kaksi',         'two',                                143, 'A1', 'numeral',     NULL),
('kolme',         'three',                              145, 'A1', 'numeral',     NULL),
('neljä',         'four',                               147, 'A1', 'numeral',     NULL),
('viisi',         'five',                               149, 'A1', 'numeral',     NULL),
('kuusi',         'six',                                151, 'A1', 'numeral',     NULL),
('seitsemän',     'seven',                              153, 'A1', 'numeral',     NULL),
('kahdeksan',     'eight',                              155, 'A1', 'numeral',     NULL),
('yhdeksän',      'nine',                               157, 'A1', 'numeral',     NULL),
('kymmenen',      'ten',                                159, 'A1', 'numeral',     NULL),
('sata',          'hundred',                            161, 'A1', 'numeral',     NULL),
('tuhat',         'thousand',                           163, 'A1', 'numeral',     NULL),
('ensimmäinen',   'first',                              165, 'A1', 'numeral',     NULL),
('toinen',        'second / another',                   167, 'A1', 'numeral',     NULL),
('kolmas',        'third',                              169, 'A1', 'numeral',     NULL),
('antaa',         'to give',                            171, 'A1', 'verb',        NULL),
('ottaa',         'to take',                            173, 'A1', 'verb',        NULL),
('saada',         'to get / to receive',                175, 'A1', 'verb',        NULL),
('tarvita',       'to need',                            177, 'A1', 'verb',        NULL),
('haluta',        'to want',                            179, 'A1', 'verb',        NULL),
('pitää',         'to like / to hold / must',           181, 'A1', 'verb',        NULL),
('täytyä',        'to have to / must',                  183, 'A1', 'verb',        NULL),
('pitää tehdä',   'to have to do',                      185, 'A1', 'verb',        NULL),
('voida',         'to be able to / can',                187, 'A1', 'verb',        NULL),
('löytää',        'to find',                            189, 'A1', 'verb',        NULL),
('tietää',        'to know (a fact)',                   191, 'A1', 'verb',        NULL),
('kysyä',         'to ask',                             193, 'A1', 'verb',        NULL),
('kertoa',        'to tell',                            196, 'A1', 'verb',        NULL),
('nähdä',         'to see',                             198, 'A1', 'verb',        NULL),
('kuulla',        'to hear',                            200, 'A1', 'verb',        NULL),
('sanoa',         'to say',                             202, 'A1', 'verb',        NULL),
('kirjoittaa',    'to write',                           204, 'A1', 'verb',        NULL),
('puhua',         'to speak',                           206, 'A1', 'verb',        NULL),
('ymmärtää',      'to understand',                      208, 'A1', 'verb',        NULL),
('oppia',         'to learn',                           210, 'A1', 'verb',        NULL),
('tulla toimeen', 'to get along / to manage',           212, 'A1', 'verb',        NULL),
('asua',          'to live / to reside',                214, 'A1', 'verb',        NULL),
('käyttää',       'to use',                             216, 'A1', 'verb',        NULL),
('avata',         'to open',                            218, 'A1', 'verb',        NULL),
('sulkea',        'to close',                           220, 'A1', 'verb',        NULL),
('odottaa',       'to wait',                            222, 'A1', 'verb',        NULL),
('auttaa',        'to help',                            224, 'A1', 'verb',        NULL),
('palata',        'to return',                          226, 'A1', 'verb',        NULL),
('lähteä',        'to leave / to depart',               228, 'A1', 'verb',        NULL),
('jäädä',         'to stay / to remain',                600, 'A2', 'verb',        NULL),
('kokeilla',      'to try / to test',                   602, 'A2', 'verb',        NULL),
('muistaa',       'to remember',                        604, 'A2', 'verb',        NULL),
('unohtaa',       'to forget',                          606, 'A2', 'verb',        NULL),
('maksaa',        'to cost / to pay',                   608, 'A2', 'verb',        NULL),
('toimia',        'to function / to act',               610, 'A2', 'verb',        NULL),
('kuulua',        'to belong to',                       612, 'A2', 'verb',        NULL),
('riittää',       'to be enough / to suffice',          614, 'A2', 'verb',        NULL),
('kasvaa',        'to grow',                            616, 'A2', 'verb',        NULL),
('tarkoittaa',    'to mean',                            618, 'A2', 'verb',        NULL),
('mahdollinen',   'possible',                           620, 'A2', 'adjective',   NULL),
('tavallinen',    'ordinary / usual',                   622, 'A2', 'adjective',   NULL),
('erilainen',     'different / varied',                 624, 'A2', 'adjective',   NULL),
('erityinen',     'special / particular',               626, 'A2', 'adjective',   NULL),
('yhteinen',      'common / shared',                    628, 'A2', 'adjective',   NULL),
('viime',         'last (week/year)',                   630, 'A2', 'adjective',   NULL),
('seuraava',      'next / following',                   632, 'A2', 'adjective',   NULL),
('ainoa',         'only / sole',                        634, 'A2', 'adjective',   NULL),
('myöhemmin',     'later',                              636, 'A2', 'adverb',      NULL),
('aikaisemmin',   'earlier',                            638, 'A2', 'adverb',      NULL),
('usein',         'often',                              640, 'A2', 'adverb',      NULL),
('harvoin',       'rarely',                             642, 'A2', 'adverb',      NULL),
('aina',          'always',                             644, 'A2', 'adverb',      NULL),
('koskaan',       'ever / never (with negation)',       646, 'A2', 'adverb',      NULL),
('jo',            'already',                            648, 'A2', 'adverb',      NULL),
('vielä',         'still / yet',                        650, 'A2', 'adverb',      NULL),
('enemmän',       'more',                               652, 'A2', 'adverb',      NULL),
('vähemmän',      'less',                               654, 'A2', 'adverb',      NULL),
('liian',         'too (much)',                         656, 'A2', 'adverb',      NULL),
('tarpeeksi',     'enough',                             658, 'A2', 'adverb',      NULL),
('yhdessä',       'together',                           660, 'A2', 'adverb',      NULL),
('yksin',         'alone',                              662, 'A2', 'adverb',      NULL),
('vastaan',       'against / toward',                   664, 'A2', 'preposition', NULL),
('ilman',         'without',                            666, 'A2', 'preposition', NULL),
('kanssa',        'with (together with)',               668, 'A2', 'preposition', NULL),
('kautta',        'through / via',                      670, 'A2', 'preposition', NULL),
('ennen',         'before',                             672, 'A2', 'preposition', NULL),
('jälkeen',       'after',                              674, 'A2', 'preposition', NULL),
('aikana',        'during',                             676, 'A2', 'preposition', NULL),
('takia',         'because of',                         678, 'A2', 'preposition', NULL),
('mukaan',        'according to / along',               680, 'A2', 'preposition', NULL),
('puolesta',      'on behalf of',                       682, 'A2', 'preposition', NULL),
('koiran',        'of the dog (genitive)',              684, 'A2', 'noun',        NULL),
('koira',         'dog',                                686, 'A2', 'noun',        NULL),
('kissa',         'cat',                                688, 'A2', 'noun',        NULL),
('lintu',         'bird',                               690, 'A2', 'noun',        NULL),
('puu',           'tree / wood',                        692, 'A2', 'noun',        NULL),
('kukka',         'flower',                             694, 'A2', 'noun',        NULL),
('väri',          'colour',                             696, 'A2', 'noun',        NULL),
('punainen',      'red',                                698, 'A2', 'adjective',   NULL),
('sininen',       'blue',                               700, 'A2', 'adjective',   NULL),
('vihreä',        'green',                              702, 'A2', 'adjective',   NULL),
('keltainen',     'yellow',                             704, 'A2', 'adjective',   NULL),
('musta',         'black',                              706, 'A2', 'adjective',   NULL),
('valkoinen',     'white',                              708, 'A2', 'adjective',   NULL),
('harmaa',        'grey',                               710, 'A2', 'adjective',   NULL),
('ruskea',        'brown',                              712, 'A2', 'adjective',   NULL),
('oranssi',       'orange',                             714, 'A2', 'adjective',   NULL),
('violetti',      'purple / violet',                    716, 'A2', 'adjective',   NULL),
('vaaleanpunainen', 'pink',                             718, 'A2', 'adjective',   NULL),
('tummansiniinen', 'dark blue / navy',                  720, 'A2', 'adjective',   NULL),
('parempi',       'better',                             722, 'A2', 'adjective',   NULL),
('huonompi',      'worse',                              724, 'A2', 'adjective',   NULL),
('isompi',        'bigger',                             726, 'A2', 'adjective',   NULL),
('pienempi',      'smaller',                            728, 'A2', 'adjective',   NULL),
('pidempi',       'longer',                             730, 'A2', 'adjective',   NULL),
('lyhyempi',      'shorter',                            732, 'A2', 'adjective',   NULL),
('nopeampi',      'faster',                             734, 'A2', 'adjective',   NULL),
('hitaampi',      'slower',                             736, 'A2', 'adjective',   NULL),
('halvempi',      'cheaper',                            738, 'A2', 'adjective',   NULL),
('kalliimpi',     'more expensive',                     740, 'A2', 'adjective',   NULL),
('kovempi',       'louder / harder',                    742, 'A2', 'adjective',   NULL),
('hiljaisempi',   'quieter',                            744, 'A2', 'adjective',   NULL),
('lähempänä',     'closer / nearer',                   746, 'A2', 'adjective',   NULL),
('kauempana',     'farther',                            748, 'A2', 'adjective',   NULL),
('kuuma',         'hot',                                750, 'A2', 'adjective',   NULL)

ON CONFLICT (base_form) DO NOTHING;
