-- Day One Sprint mnemonics
-- 165 high-frequency words with sound-bridge memory aids.
-- Pronunciation guide: y=/y/ "ew" (ROUNDED, like few); ö=/ø/ "ur" (no r);
-- ä=/æ/ "a" as in cat; au="ow" as in cow; ai="eye"; j=English "y".
-- Stress is ALWAYS on the first syllable.
INSERT INTO mnemonics (word_id, text, is_public)
SELECT w.id, m.text, true
FROM (VALUES
  ('talo',        'TAL-oh — imagine a TALL building. That is your Finnish house.'),
  ('auto',        'AU-to — "OW" as in cow, plus "toh": say "OW-toh". Not English "aw-to". A CAR.'),
  ('ihminen',     'IH-mi-nen — sounds like "I''m in" — I''m in the human race. A person.'),
  ('ruoka',       'ROO-ka — ROO sounds like "roo" in kangaroo eating FOOD from a pouch.'),
  ('vesi',        'VEH-si — VEH sounds like "wet" — wet things need WATER.'),
  ('työ',         'TYÖ — round your lips for "ew" and glide to "ur": one tight syllable. WORK.'),
  ('koira',       'KOI-ra — a KOI fish wearing a dog collar. That is your DOG.'),
  ('kauppa',      'KAU-pa — "KOWP-pa": "au" = "ow" as in cow. SHOP.'),
  ('puhelin',     'POO-he-lin — POOL-in-line: people queue at the PHONE booth.'),
  ('ovi',         'OH-vi — OH VEE! Someone left the DOOR open!'),
  ('ikkuna',      'IK-ku-na — ICK-una: you lick the WINDOW and it tastes icky.'),
  ('kaupunki',    'KAU-pun-ki — sounds like "cowpunk city" — a wild CITY.'),
  ('perhe',       'PER-he — PER-HEY: hey, that is my FAMILY over there!'),
  ('ystävä',      'YS-tä-vä — "HEWS-ta-va": rounded "ew", "ta" as in cat. Your FRIEND.'),
  ('aika',        'AI-ka — "EYE-ka": "ai" sounds like "eye". TIME.'),
  ('päivä',       'PÄI-vä — "PIE-va": "äi" = "pie" (eye), "va" as in cat. DAY.'),
  ('yö',          'YÖ — "ew" gliding into "ur", lips rounded throughout. NIGHT.'),
  ('vuosi',       'VOO-si — VOO-see: you can vaguely see the whole YEAR ahead.'),
  ('kuukausi',    'KOO-kau-si — COO-COW-si: a cool cow comes once a MONTH.'),
  ('viikko',      'VIIK-ko — WEEK-oh: a WEEK goes by in a flicker.'),
  ('tunti',       'TOON-ti — TUNE-tea: a HOUR-long music tune with tea.'),
  ('mies',        'MI-es — ME-es: "Me is a MAN" — easy shortcut.'),
  ('nainen',      'NAI-nen — NYE-nen: on New Year''s Eve a WOMAN makes a wish.'),
  ('lapsi',       'LAP-si — LAP-see: a CHILD sits on your lap.'),
  ('poika',       'POI-ka — POI-ka: a POI dancer who is a BOY.'),
  ('tyttö',       'TYT-tö — "TEWT-tur": rounded lips on both vowels. A GIRL.'),
  ('äiti',        'ÄI-ti — "a" (cat) gliding to "ee", making "EYE-tee". MOTHER.'),
  ('isä',         'I-sä — EE-sah: EASY-ah — FATHER makes things easy.'),
  ('veli',        'VEL-i — VEIL-ee: your BROTHER lifts the veil at a wedding.'),
  ('sisar',       'SI-sar — SEE-sar: your SISTER says "see-sar!" like Caesar.'),
  ('koulu',       'KOU-lu — "KOH" gliding to "oo": say "KOH-oo-loo". SCHOOL.'),
  ('lääkäri',     'LÄÄ-kä-ri — long "AA" as in a sheep''s "baa", then "ka-ri". DOCTOR.'),
  ('sairaala',    'SAI-raa-la — SIGH-rah-la: you SIGH when entering the HOSPITAL.'),
  ('bussi',       'BOOS-si — BOOZY: a tipsy BUS driver — only in your imagination!'),
  ('juna',        'JU-na — "j" is English "y"! Say "YOO-na". A TRAIN.'),
  ('lentokone',   'LEN-to-ko-ne — LENTO-CONE: a slow (lento) cone-shaped AEROPLANE.'),
  ('hotelli',     'HO-tel-li — HOTEL — same word in Finnish. Easy!'),
  ('ravintola',   'RA-vin-to-la — RAV-into-la: you rave into a la-la RESTAURANT.'),
  ('kahvila',     'KAH-vi-la — KAH-VEE-la: a CAFÉ where you go kah-vee (coffee) la-la.'),
  ('kirjasto',    'KIR-jas-to — "KEER-yas-toh": "j" = "y", rolled r. LIBRARY.'),
  ('puisto',      'PUIS-to — "POO-ees-toh": "p" not "b". A PARK.'),
  ('meri',        'MEH-ri — MERRY: the SEA makes you merry.'),
  ('järvi',       'JÄR-vi — "YAR-vee": "j" = English "y", "ä" as in cat. LAKE.'),
  ('metsä',       'MET-sä — "MET-sa": "a" as in cat. FOREST.'),
  ('sää',         'SÄÄ — long "AA" like a sheep''s "baa". WEATHER.'),
  ('aurinko',     'AU-rin-ko — "OW-rin-koh": "ow" as in cow. THE SUN.'),
  ('lumi',        'LOO-mi — LOOMY: everything is gloomy when SNOW covers the ground.'),
  ('sade',        'SA-de — SAH-deh: "Ah, sad-eh" — RAIN makes you a little sad.'),
  ('tuuli',       'TOO-li — TOOLEY: the WIND blows tools across Tooley Street.'),
  ('lämpö',       'LÄM-pö — "LAM" (as in cat) + "pur" (as in fur, no r). WARMTH.'),
  ('iso',         'I-so — EE-so: ISO means BIG in photography too.'),
  ('pieni',       'PIE-ni — PEE-nee: a teeny tiny SMALL pea.'),
  ('hyvä',        'HY-vä — "HEW-va": round your lips for "ew" (like few), "va" as in cat. GOOD.'),
  ('huono',       'HOO-no — HOO-no: "Hoo no, that is BAD news!"'),
  ('kaunis',      'KAU-nis — COW-nis: a BEAUTIFUL cow? In Finland, maybe!'),
  ('kylmä',       'KYL-mä — "KEWL-ma": rounded "ew", "ma" as in cat. COLD.'),
  ('lämmin',      'LÄM-min — LAMM-in: a lamb in a WARM woolly coat.'),
  ('nopea',       'NO-pe-a — NOH-peh-ah: "No rush? Be FAST!"'),
  ('hidas',       'HI-das — HEE-dahs: "Heeda'' slow down" — SLOW.'),
  ('vanha',       'VAN-ha — VAN-ha: an OLD van that hardly moves.'),
  ('nuori',       'NUO-ri — "NOO-oh-ree". YOUNG.'),
  ('uusi',        'OO-si — OO-see: "Ooh, I SEE a NEW one!"'),
  ('kallis',      'KAL-lis — CALL-is: it COSTS so much to make a CALL.'),
  ('halpa',       'HAL-pa — HAL-pa: HALf-price is CHEAP. Ha! Half price!'),
  ('pitkä',       'PIT-kä — PIT-ka: a PIT is LONG and deep.'),
  ('lyhyt',       'LY-hyt — "LEW-hewt": BOTH vowels get the rounded "ew". SHORT.'),
  ('vahva',       'VAH-va — VAH-va: "VAVA vroom" — a STRONG engine.'),
  ('heikko',      'HEIK-ko — HAYK-oh: "Hay-ko that is WEAK!" said the wrestler.'),
  ('avoin',       'A-voin — AH-vo-in: "Ah, the OPEN avocado is in."'),
  ('suljettu',    'SUL-jet-tu — "SOOL-yet-too": "j" = "y". CLOSED.'),
  ('helppo',      'HEL-ppo — HEL-poh: "Help-oh, that was EASY after all!"'),
  ('vaikea',      'VAI-ke-a — WHY-key-ah: "WHY is this key-ah so DIFFICULT?"'),
  ('tärkeä',      'TÄR-ke-ä — "TAR" (a as in cat) + "keh-a". IMPORTANT.'),
  ('hauska',      'HAUS-ka — HOUSE-ka: "That house party is FUN!"'),
  ('surullinen',  'SU-rul-li-nen — SUE-ROOL-ee-nen: a SAD person suing while rolling.'),
  ('iloinen',     'I-loi-nen — EE-loy-nen: "Ee, a loyal hen — how HAPPY!"'),
  ('väsynyt',     'VÄ-sy-nyt — "VA-sew-newt": "va" as in cat, then rounded "ew" twice. TIRED.'),
  ('nälkäinen',   'NÄL-käi-nen — NAL-kine-en: "NAL-kine-en" — HUNGRY like a wolf.'),
  ('janoinen',    'YA-noi-nen — YAH-noy-nen: "Yah! Noisy stomach means THIRSTY."'),
  ('terve',       'TER-ve — TER-veh: "Terve!" — the standard Finnish HELLO.'),
  ('sairas',      'SAI-ras — SIGH-ras: you SIGH when you are ILL.'),
  ('olla',        'OL-la — OL-la: "OLLA — TO BE or not to be!"'),
  ('tulla',       'TOO-la — TOO-la: "Too-la, I need TO COME here."'),
  ('mennä',       'MEN-nä — "MEN-na": "na" as in cat. TO GO.'),
  ('saada',       'SAA-da — SAH-da: "SAH-da gift — TO GET something."'),
  ('voida',       'VOI-da — VOY-da: "Voyage — TO BE ABLE to sail."'),
  ('täytyä',      'TÄY-ty-ä — "ta" (cat) gliding to "ew", then "tew-a". MUST.'),
  ('antaa',       'AN-taa — AN-tah: "An-tah — TO GIVE it on a tray."'),
  ('ottaa',       'OT-taa — OT-tah: "Ot-tah — TO TAKE it and go."'),
  ('tehdä',       'TEH-dä — "TEH-da": "da" as in cat. TO DO or not to do.'),
  ('sanoa',       'SA-no-a — SAH-no-ah: "SAH, no-ah — TO SAY nothing."'),
  ('tietää',      'TIE-tää — "TYEH-taa": "ie" glides ee-eh, long "aa" like baa. TO KNOW.'),
  ('nähdä',       'NÄH-dä — "NA-da": "a" as in cat. TO SEE.'),
  ('kuulla',      'KOOL-la — COOL-la: "Cool-la TO HEAR cool sounds."'),
  ('lukea',       'LOO-ke-a — LUKE-ee-ah: "Luke-ee-ah — TO READ like a Jedi."'),
  ('kirjoittaa',  'KIR-yoit-taa — KEER-yoit-tah: "keer-yoit-tah — TO WRITE quickly."'),
  ('ostaa',       'OS-taa — OS-tah: "OS-tah — TO BUY the OS for your computer."'),
  ('maksaa',      'MAK-saa — MAX-ah: "MAX-ah price — TO PAY maximum."'),
  ('asua',        'A-su-a — AH-soo-ah: "Ah, sue-ah — TO LIVE and face lawsuits."'),
  ('opiskella',   'O-pis-kel-la — OH-pis-kel-la: "Oh, piccolo-la — TO STUDY music."'),
  ('rakastaa',    'RA-kas-taa — "RAH-kas-taa": "a" as in father, long "aa" at the end. TO LOVE.'),
  ('haluta',      'HA-lu-ta — HAH-loo-ta: "Hah! Loota — TO WANT the loot."'),
  ('tarvita',     'TAR-vi-ta — TAR-vee-tah: "Tar-vee-tah — TO NEED tar on the road."'),
  ('löytää',      'LÖY-tää — "LUR" gliding to "ee", then long "aa" (like baa). TO FIND.'),
  ('lähteä',      'LÄH-te-ä — "LA-te-a": "a" as in cat, like a latte to go. TO LEAVE.'),
  ('odottaa',     'O-dot-taa — OH-dot-tah: "Oh dot-tah — TO WAIT, connecting dots."'),
  ('kysyä',       'KY-sy-ä — "KEW-sew-a": rounded "ew", not "kee". TO ASK.'),
  ('vastata',     'VAS-ta-ta — VAS-tah-tah: "Vast-ah-tah — TO ANSWER vastly."'),
  ('soittaa',     'SOIT-taa — SOY-tah: "Soy-tah — TO CALL or TO PLAY music."'),
  ('katsoa',      'KAT-so-a — KAT-so-ah: "KAT-so-ah — TO WATCH the cat."'),
  ('syödä',       'SYÖ-dä — "sew" gliding to "ur", then "da". TO EAT.'),
  ('juoda',       'YOO-da — YOO-da: "Yooda drinks — TO DRINK like Yoda."'),
  ('nukkua',      'NOOK-koo-a — NOOK-oo-ah: "NOOK-oo-ah — TO SLEEP in your reading nook."'),
  ('herätä',      'HE-rä-tä — "HEH-ra-ta": "rä" and "tä" both "a" as in cat. TO WAKE UP.'),
  ('kävellä',     'KÄ-vel-lä — "KA-vel-la": "a" as in cat throughout. TO WALK.'),
  ('pelata',      'PE-la-ta — PEH-lah-tah: "Peh-la-ta — TO PLAY — pelota ball game."'),
  ('laulaa',      'LAU-laa — LAU-lah: "LAU-lah — TO SING la-la-la."'),
  ('minä',        'MI-nä — MEE-nah: "ME-nah — I, ME myself."'),
  ('sinä',        'SI-nä — SEE-nah: "SEE-nah — YOU, I see you."'),
  ('hän',         'HÄN — HAN: HAN Solo is HE or SHE in Finnish — gender neutral!'),
  ('me',          'ME — ME: WE, as in US, ME and you together.'),
  ('te',          'TE — TEH: YOU (plural) — "Teh, you lot!"'),
  ('he',          'HE — HEH: THEY — "Heh, they did it!"'),
  ('tämä',        'TÄ-mä — "TAM-ma": "a" as in cat, both syllables. THIS one right here.'),
  ('tuo',         'TUO — "TOO-oh": "uo" glides from "oo" to "oh". THAT one over there.'),
  ('se',          'SE — "SEH": IT. Short and simple.'),
  ('kuka',        'KOO-ka — KOO-ka: "KOO-KA-burra — WHO is that bird?"'),
  ('mikä',        'MI-kä — MEE-ka: "MEE-ka — WHAT is that? MICA mineral?"'),
  ('missä',       'MIS-sä — "MIS-sa": "a" as in cat. WHERE?'),
  ('milloin',     'MIL-loin — MIL-loyn: "MIL-loyn — WHEN will the million arrive?"'),
  ('miksi',       'MIK-si — MICK-see: "MICK-see — WHY, Mick, why?"'),
  ('miten',       'MI-ten — MEE-ten: "MEE-ten — HOW do you meet ten people?"'),
  ('yksi',        'YK-si — "EWK-see": rounded "ew". ONE.'),
  ('kaksi',       'KAK-si — KAK-see: "KAK-see — TWO cakes."'),
  ('kolme',       'KOL-me — KOL-meh: "COAL-me — THREE lumps of coal."'),
  ('neljä',       'NEL-jä — "NEL-ya": "j" = "y", "a" as in cat. FOUR.'),
  ('viisi',       'VEE-si — VEE-see: "VEE-see — FIVE V-signs."'),
  ('kuusi',       'KOO-si — KOO-see: "GOOSE-ee — SIX geese a-laying."'),
  ('seitsemän',   'SEIT-se-män — SAYT-se-man: "SEVEN-man team said SAYT-se-man."'),
  ('kahdeksan',   'KAH-dek-san — KAH-deck-san: "KAH-deck-SAND castle — EIGHT towers."'),
  ('yhdeksän',    'YH-dek-sän — "EWH-dek-san": rounded "ew", "san" as in cat. NINE.'),
  ('kymmenen',    'KYM-me-nen — "KEWM-me-nen": rounded "ew". TEN.'),
  ('kiitos',      'KII-tos — KEE-tos: "KEY-toss — THANK YOU for tossing the key."'),
  ('ole hyvä',    'O-le HY-vä — "OH-leh HEW-va": rounded lips on "hew", not "hee". YOU''RE WELCOME.'),
  ('anteeksi',    'AN-teek-si — ON-teek-see: "On-teek-see antiques — EXCUSE ME."'),
  ('kyllä',       'KYL-lä — "KEWL-la": rounded "ew", "la" as in cat. YES.'),
  ('ei',          'EI — AY: "AY NO! EI means NO."'),
  ('ehkä',        'EH-kä — "EH-ka": "a" as in cat. MAYBE.'),
  ('nyt',         'NYT — like the amphibian "NEWT", rounded "ew". NOW.'),
  ('sitten',      'SIT-ten — sit down, THEN relax. THEN.'),
  ('tässä',       'TÄS-sä — "TAS-sa": "a" as in cat, both times. HERE.'),
  ('siellä',      'SIEL-lä — "SYEL-la": "ie" glides ee-eh, "la" as in cat. THERE.'),
  ('kotona',      'KO-to-na — "KOH-toh-nah": a cozy tonal feeling. AT HOME.')
) AS m(base_form, text)
JOIN words w ON w.base_form = m.base_form
WHERE NOT EXISTS (
  SELECT 1 FROM mnemonics x WHERE x.word_id = w.id AND x.user_id IS NULL
);
