-- Day One Sprint mnemonics
-- 180 high-frequency words with sound-bridge memory aids.
INSERT INTO mnemonics (word_id, text, is_public)
SELECT w.id, m.text, true
FROM (VALUES
  ('talo',        'TAL-oh — imagine a TALL building. That is your Finnish house.'),
  ('auto',        'AUTO — Finnish kept the international word. Same as English!'),
  ('ihminen',     'IH-mi-nen — sounds like "I''m in" — I''m in the human race. A person.'),
  ('ruoka',       'ROO-ka — ROO sounds like "roo" in kangaroo eating FOOD from a pouch.'),
  ('vesi',        'VEH-si — VEH sounds like "wet" — wet things need WATER.'),
  ('työ',        'TYO — sounds like "two" hands doing hard WORK every day.'),
  ('koira',       'KOI-ra — a KOI fish wearing a dog collar. That is your DOG.'),
  ('kauppa',      'KAUP-pa — KAUPpa sounds like "cop" guarding the SHOP.'),
  ('puhelin',     'POO-he-lin — POOL-in-line: people queue at the PHONE booth.'),
  ('ovi',         'OH-vi — OH VEE! Someone left the DOOR open!'),
  ('ikkuna',      'IK-ku-na — ICK-una: you lick the WINDOW and it tastes icky.'),
  ('kaupunki',    'KAU-pun-ki — sounds like "cowpunk city" — a wild CITY.'),
  ('perhe',       'PER-he — PER-HEY: hey, that is my FAMILY over there!'),
  ('ystävä',      'YS-tä-vä — EAST-a-va: your best FRIEND came from the east.'),
  ('aika',        'AI-ka — AY-ka: "Ay, there is no TIME to waste!"'),
  ('päivä',       'PÄI-vä — PIE-vah: you eat pie every DAY.'),
  ('yö',          'YO — YO! It is NIGHT time, go to sleep.'),
  ('vuosi',       'VOO-si — VOO-see: you can vaguely see the whole YEAR ahead.'),
  ('kuukausi',    'KOO-kau-si — COO-COW-si: a cool cow comes once a MONTH.'),
  ('viikko',      'VIIK-ko — WEEK-oh: a WEEK goes by in a flicker.'),
  ('tunti',       'TOON-ti — TUNE-tea: a HOUR-long music tune with tea.'),
  ('mies',        'MI-es — ME-es: "Me is a MAN" — easy shortcut.'),
  ('nainen',      'NAI-nen — NYE-nen: on New Year''s Eve a WOMAN makes a wish.'),
  ('lapsi',       'LAP-si — LAP-see: a CHILD sits on your lap.'),
  ('poika',       'POI-ka — POI-ka: a POI dancer who is a BOY.'),
  ('tyttö',       'TYT-tö — TIT-oh: a tiny tot — that is the GIRL.'),
  ('äiti',        'ÄI-ti — AY-tee: "Ay tee" sounds like auntie but means MOTHER.'),
  ('isä',         'I-sä — EE-sah: EASY-ah — FATHER makes things easy.'),
  ('veli',        'VEL-i — VEIL-ee: your BROTHER lifts the veil at a wedding.'),
  ('sisar',       'SI-sar — SEE-sar: your SISTER says "see-sar!" like Caesar.'),
  ('koulu',       'KO-lu — KOH-loo: you SCHOOL yourself until you glow.'),
  ('lääkäri',     'LÄÄ-kä-ri — LAY-car-ee: the DOCTOR drives a lay-back car.'),
  ('sairaala',    'SAI-raa-la — SIGH-rah-la: you SIGH when entering the HOSPITAL.'),
  ('bussi',       'BOOS-si — BOOZY: a tipsy BUS driver — only in your imagination!'),
  ('juna',        'YOO-na — JUNE-ah: in June the TRAIN runs on schedule.'),
  ('lentokone',   'LEN-to-ko-ne — LENTO-CONE: a slow (lento) cone-shaped AEROPLANE.'),
  ('hotelli',     'HO-tel-li — HOTEL — same word in Finnish. Easy!'),
  ('ravintola',   'RA-vin-to-la — RAV-into-la: you rave into a la-la RESTAURANT.'),
  ('kahvila',     'KAH-vi-la — KAH-VEE-la: a CAFÉ where you go kah-vee (coffee) la-la.'),
  ('kirjasto',    'KIR-jas-to — CURE-jaws-toe: a LIBRARY cures your jaw and toe boredom.'),
  ('puisto',      'POOS-to — BOOST-oh: a PARK gives you an energy boost.'),
  ('meri',        'MEH-ri — MERRY: the SEA makes you merry.'),
  ('järvi',       'YÄR-vi — YARR-vee: a pirate (yarr) sails the Finnish LAKE.'),
  ('metsä',       'MET-sä — MET-sah: you MET someone in the FOREST.'),
  ('sää',         'SÄÄ — SAY: "Say, what is the WEATHER like today?"'),
  ('aurinko',     'AU-rin-ko — OR-in-go: the SUN says "or-in-go, shine or go."'),
  ('lumi',        'LOO-mi — LOOMY: everything is gloomy when SNOW covers the ground.'),
  ('sade',        'SA-de — SAH-deh: "Ah, sad-eh" — RAIN makes you a little sad.'),
  ('tuuli',       'TOO-li — TOOLEY: the WIND blows tools across Tooley Street.'),
  ('lämpö',       'LÄM-pö — LAMP-oh: a LAMP gives WARMTH and heat.'),
  ('iso',         'I-so — EE-so: ISO means BIG in photography too.'),
  ('pieni',       'PIE-ni — PEE-nee: a teeny tiny SMALL pea.'),
  ('hyvä',        'HY-vä — HEE-vah: "Heave-ah, that is GOOD work!"'),
  ('huono',       'HOO-no — HOO-no: "Hoo no, that is BAD news!"'),
  ('kaunis',      'KAU-nis — COW-nis: a BEAUTIFUL cow? In Finland, maybe!'),
  ('kylmä',       'KYL-mä — KILL-ma: the COLD tries to KILL ya.'),
  ('lämmin',      'LÄM-min — LAMM-in: a lamb in a WARM woolly coat.'),
  ('nopea',       'NO-pe-a — NO-pay-ah: "No pay? Ah, be FAST and run!"'),
  ('hidas',       'HI-das — HEE-dahs: "Heeda'' slow down" — SLOW.'),
  ('vanha',       'VAN-ha — VAN-ha: an OLD van that hardly moves.'),
  ('nuori',       'NOO-ri — NEWRY: a YOUNG person new to the city of Newry.'),
  ('uusi',        'OO-si — OO-see: "Ooh, I SEE a NEW one!"'),
  ('kallis',      'KAL-lis — CALL-is: it COSTS so much to make a CALL.'),
  ('halpa',       'HAL-pa — HAL-pa: HALf-price is CHEAP. Ha! Half price!'),
  ('pitkä',       'PIT-kä — PIT-ka: a PIT is LONG and deep.'),
  ('lyhyt',       'LY-hyt — LEW-hit: a SHORT little hit song.'),
  ('vahva',       'VAH-va — VAH-va: "VAVA vroom" — a STRONG engine.'),
  ('heikko',      'HEIK-ko — HAYK-oh: "Hay-ko that is WEAK!" said the wrestler.'),
  ('avoin',       'A-voin — AH-vo-in: "Ah, the OPEN avocado is in."'),
  ('suljettu',    'SUL-jet-tu — SOUL-jet-too: the CLOSED soul jet is too full to board.'),
  ('helppo',      'HEL-ppo — HEL-poh: "Help-oh, that was EASY after all!"'),
  ('vaikea',      'VAI-ke-a — WHY-key-ah: "WHY is this key-ah so DIFFICULT?"'),
  ('tärkeä',      'TÄR-ke-ä — TURKEY-ah: "That turkey is IMPORTANT for Thanksgiving."'),
  ('hauska',      'HAUS-ka — HOUSE-ka: "That house party is FUN!"'),
  ('surullinen',  'SU-rul-li-nen — SUE-ROOL-ee-nen: a SAD person suing while rolling.'),
  ('iloinen',     'I-loi-nen — EE-loy-nen: "Ee, a loyal hen — how HAPPY!"'),
  ('väsynyt',     'VÄ-sy-nyt — VEH-sin-it: "VEH, seen it all" — totally TIRED.'),
  ('nälkäinen',   'NÄL-käi-nen — NAL-kine-en: "NAL-kine-en" — HUNGRY like a wolf.'),
  ('janoinen',    'YA-noi-nen — YAH-noy-nen: "Yah! Noisy stomach means THIRSTY."'),
  ('terve',       'TER-ve — TER-veh: "Turvy topsy-tervy — HEALTHY upside down!"'),
  ('sairas',      'SAI-ras — SIGH-ras: you SIGH when you are ILL.'),
  ('olla',        'OL-la — OL-la: "OLLA — TO BE or not to be!"'),
  ('tulla',       'TOO-la — TOO-la: "Too-la, I need TO COME here."'),
  ('mennä',       'MEN-nä — MEN-nah: "MEN, nah — I have TO GO alone."'),
  ('saada',       'SAA-da — SAH-da: "SAH-da gift — TO GET something."'),
  ('voida',       'VOI-da — VOY-da: "Voyage — TO BE ABLE to sail."'),
  ('täytyä',      'TÄY-ty-ä — TAY-tya: "Tay tea — you MUST have it."'),
  ('antaa',       'AN-taa — ON-tah: "On-tah — TO GIVE it on a tray."'),
  ('ottaa',       'OT-taa — OT-tah: "Ot-tah — TO TAKE it and go."'),
  ('tehdä',       'TEH-dä — TEH-dah: "Teh-dah — TO DO or not to do."'),
  ('sanoa',       'SA-no-a — SAH-no-ah: "SAH, no-ah — TO SAY nothing."'),
  ('tietää',      'TIE-tää — TYEH-tah: "Tie-tah — TO KNOW how to tie a tie."'),
  ('nähdä',       'NÄH-dä — NAH-dah: "Nah-dah, TO SEE nothing here."'),
  ('kuulla',      'KOOL-la — COOL-la: "Cool-la TO HEAR cool sounds."'),
  ('lukea',       'LOO-ke-a — LUKE-ee-ah: "Luke-ee-ah — TO READ like a Jedi."'),
  ('kirjoittaa',  'KIR-yoit-taa — KEER-yoit-tah: "keer-yoit-tah — TO WRITE quickly."'),
  ('ostaa',       'OS-taa — OS-tah: "OS-tah — TO BUY the OS for your computer."'),
  ('maksaa',      'MAK-saa — MAX-ah: "MAX-ah price — TO PAY maximum."'),
  ('asua',        'A-su-a — AH-soo-ah: "Ah, sue-ah — TO LIVE and face lawsuits."'),
  ('opiskella',   'O-pis-kel-la — OH-pis-kel-la: "Oh, piccolo-la — TO STUDY music."'),
  ('rakastaa',    'RA-kas-taa — RAH-kus-tah: "RAH! Kustard — TO LOVE custard."'),
  ('haluta',      'HA-lu-ta — HAH-loo-ta: "Hah! Loota — TO WANT the loot."'),
  ('tarvita',     'TAR-vi-ta — TAR-vee-tah: "Tar-vee-tah — TO NEED tar on the road."'),
  ('löytää',      'LÖY-tää — LOY-tah: "LOYAL-tah — TO FIND a loyal friend."'),
  ('lähteä',      'LÄH-te-ä — LAH-te-ah: "Lah-te-ah — TO LEAVE like a latte to go."'),
  ('odottaa',     'O-dot-taa — OH-dot-tah: "Oh dot-tah — TO WAIT, connecting dots."'),
  ('kysyä',       'KY-sy-ä — KEE-sya: "KEY-sya — TO ASK for the key."'),
  ('vastata',     'VAS-ta-ta — VAS-tah-tah: "Vast-ah-tah — TO ANSWER vastly."'),
  ('soittaa',     'SOIT-taa — SOY-tah: "Soy-tah — TO CALL or TO PLAY music."'),
  ('katsoa',      'KAT-so-a — KAT-so-ah: "KAT-so-ah — TO WATCH the cat."'),
  ('syödä',       'SYÖ-dä — SYOH-dah: "See-oh-da — TO EAT see-food."'),
  ('juoda',       'YOO-da — YOO-da: "Yooda drinks — TO DRINK like Yoda."'),
  ('nukkua',      'NOOK-koo-a — NOOK-oo-ah: "NOOK-oo-ah — TO SLEEP in your reading nook."'),
  ('herätä',      'HE-rä-tä — HEH-rah-tah: "HEH-rah-tah — TO WAKE UP, heh!"'),
  ('kävellä',     'KÄ-vel-lä — KAH-vel-lah: "Cavell-ah — TO WALK like Edith Cavell."'),
  ('pelata',      'PE-la-ta — PEH-lah-tah: "Peh-la-ta — TO PLAY — pelota ball game."'),
  ('laulaa',      'LAU-laa — LAU-lah: "LAU-lah — TO SING la-la-la."'),
  ('minä',        'MI-nä — MEE-nah: "ME-nah — I, ME myself."'),
  ('sinä',        'SI-nä — SEE-nah: "SEE-nah — YOU, I see you."'),
  ('hän',         'HÄN — HAN: HAN Solo is HE or SHE in Finnish — gender neutral!'),
  ('me',          'ME — ME: WE, as in US, ME and you together.'),
  ('te',          'TE — TEH: YOU (plural) — "Teh, you lot!"'),
  ('he',          'HE — HEH: THEY — "Heh, they did it!"'),
  ('tämä',        'TÄ-mä — TAH-mah: "Tah-mah — THIS thing here."'),
  ('tuo',         'TOO — TOO: THAT over there — "too far away."'),
  ('se',          'SE — SEH: IT — short and simple.'),
  ('kuka',        'KOO-ka — KOO-ka: "KOO-KA-burra — WHO is that bird?"'),
  ('mikä',        'MI-kä — MEE-ka: "MEE-ka — WHAT is that? MICA mineral?"'),
  ('missä',       'MIS-sä — MIS-sah: "MISS-ah — WHERE is my miss?"'),
  ('milloin',     'MIL-loin — MIL-loyn: "MIL-loyn — WHEN will the million arrive?"'),
  ('miksi',       'MIK-si — MICK-see: "MICK-see — WHY, Mick, why?"'),
  ('miten',       'MI-ten — MEE-ten: "MEE-ten — HOW do you meet ten people?"'),
  ('yksi',        'YK-si — YEK-see: "YECK-see — ONE yucky thing."'),
  ('kaksi',       'KAK-si — KAK-see: "KAK-see — TWO cakes."'),
  ('kolme',       'KOL-me — KOL-meh: "COAL-me — THREE lumps of coal."'),
  ('neljä',       'NEL-jä — NEL-yah: "NELL-yah — FOUR Nellies."'),
  ('viisi',       'VEE-si — VEE-see: "VEE-see — FIVE V-signs."'),
  ('kuusi',       'KOO-si — KOO-see: "GOOSE-ee — SIX geese a-laying."'),
  ('seitsemän',   'SEIT-se-män — SAYT-se-man: "SEVEN-man team said SAYT-se-man."'),
  ('kahdeksan',   'KAH-dek-san — KAH-deck-san: "KAH-deck-SAND castle — EIGHT towers."'),
  ('yhdeksän',    'YH-dek-sän — YEH-deck-san: "YEAH-deck-san — NINE decks on a ship."'),
  ('kymmenen',    'KYM-me-nen — KIM-me-nen: "KIM-me-nen — TEN Kims."'),
  ('kiitos',      'KII-tos — KEE-tos: "KEY-toss — THANK YOU for tossing the key."'),
  ('ole hyvä',    'O-le HY-vä — OH-leh HEE-vah: "Oh-leh heave-ah — YOU''RE WELCOME, here you go."'),
  ('anteeksi',    'AN-teek-si — ON-teek-see: "On-teek-see antiques — EXCUSE ME."'),
  ('kyllä',       'KYL-lä — KIL-lah: "KILL-ah, YES, kill it with kindness."'),
  ('ei',          'EI — AY: "AY NO! EI means NO."'),
  ('ehkä',        'EH-kä — EH-kah: "EH-kah — MAYBE, eh, could be."'),
  ('nyt',         'NYT — NOOT: "NOOT, noot — NOW, penguin!"'),
  ('sitten',      'SIT-ten — SIT-ten: "SIT-ten — THEN sit down."'),
  ('tässä',       'TÄS-sä — TAS-sah: "TASSAH — HERE, have a tasse of coffee."'),
  ('siellä',      'SIEL-lä — SYEL-lah: "SIEL-lah — THERE, over there."'),
  ('kotona',      'KO-to-na — KOH-toh-nah: "KOH-toh-nah — AT HOME, cozy."')
) AS m(base_form, text)
JOIN words w ON w.base_form = m.base_form
ON CONFLICT DO NOTHING;
