// scripts/ingest/lib/sql.mjs
//
// SQL string helpers for emitting idempotent seed files. The whole point of
// this pipeline is that nobody hand-types Finnish into SQL again, so the only
// place values become SQL is right here, where escaping is centralised.

/**
 * Quote a value as a SQL string literal, doubling embedded single quotes.
 * Pass null/undefined to get a bare NULL.
 * @param {string|null|undefined} value
 * @returns {string}
 */
export function sqlStr(value) {
  if (value === null || value === undefined) return 'NULL'
  return `'${String(value).replace(/'/g, "''")}'`
}

/**
 * Quote a value or emit NULL when empty/blank. Used for optional columns
 * (puhekieli, ipa, part_of_speech) so we never ship an empty string where the
 * data is genuinely unknown.
 * @param {string|null|undefined} value
 * @returns {string}
 */
export function sqlStrOrNull(value) {
  if (value === null || value === undefined) return 'NULL'
  const t = String(value).trim()
  return t.length === 0 ? 'NULL' : sqlStr(t)
}

/** A bare integer literal, or NULL. @param {number|null|undefined} n */
export function sqlInt(n) {
  return n === null || n === undefined || Number.isNaN(n) ? 'NULL' : String(Math.trunc(n))
}

/**
 * `(SELECT id FROM topics WHERE slug = '...')` subselect, matching the style of
 * the existing seeds, or NULL when the word/sentence has no curated topic.
 * @param {string|null|undefined} slug
 */
export function topicSubselect(slug) {
  if (!slug) return 'NULL'
  return `(SELECT id FROM topics WHERE slug = ${sqlStr(slug)})`
}

/**
 * A provenance/attribution banner for the top of a generated seed file.
 * Records exactly which CC source produced the data and when, so the
 * attribution can never drift from reality again.
 * @param {{ title: string, sources: string[], notes?: string[] }} meta
 */
export function header({ title, sources, notes = [] }) {
  const stamp = new Date().toISOString().slice(0, 10)
  const lines = [
    `-- ${title}`,
    `-- GENERATED by scripts/ingest on ${stamp} — do not hand-edit; re-run the builder.`,
    `-- Sources (Creative Commons; see scripts/ingest/README.md for full attribution):`,
    ...sources.map((s) => `--   - ${s}`),
    ...notes.map((n) => `-- NOTE: ${n}`),
    '',
  ]
  return lines.join('\n')
}
